.TH ENCLOV-STOP 1 "June 2025" "v0.1.0" "Enclov AI CLI Manual"
.SH NAME
enclov-stop \- Stops the running Enclov-AI container services gracefully.
.SH SYNOPSIS
.B enclov stop
.SH DESCRIPTION
Stops the running Enclov-AI container services gracefully.
.SH OPTIONS
.TP
.BR --help
Show usage information for the stop command and exit.
.SH EXAMPLES
.EX
$ enclov stop
.EE
.SH EXIT STATUS
.TP
.B 0
Successfully stopped
.TP
.B 1
Error stopping services or containers not running
.SH SEE ALSO
.BR enclov (1)
.BR enclov-start (1)
.BR enclov-status (1)
.SH AUTHOR
Written by Kubu Lee.

.SH COPYRIGHT
MIT License © 2025 Web4application
